### ISSUE TITLE
cap S reworking

### ISSUE THREAD

**Issue by tphinney** [batsimadz/Sankofa-Display#1]
Some folks have noted that the center portion of the cap S could be seen as an undesirable symbol. Although many people have looked at the S without making this observation, I must say that for me at least, once seen it can’t easily be unseen.  :(

As you have discussed with Nate, we are looking to see a revised version of the S that does not have this problem.

**Comment by batsimadz** [comment]
Thanks for the observation, Thomas. I have revised the shape.
