### ISSUE TITLE
Strokes thickness inconsistencies

### ISSUE THREAD

**Issue by LisaHuang2017** [batsimadz/Sankofa-Display#10]
From the file of Sankofa as of Jan 23, 2024, here are my comments on some inconsistent stroke thicknesses:
- [ ] horizontal bar of Eth (and Dcroat) are different, but they should be the same, and the one on the right seems more consistent with the general letter (the one on the middle has a too thin horizontal stroke)
<img width="363" alt="Capture d’écran 2024-01-23 à 19 24 30" src="https://github.com/batsimadz/Sankofa-Display/assets/32390132/46c70610-61ff-4200-9e66-0907f3977e2c">

- [ ] Iota-latin is too thick
<img width="327" alt="Capture d’écran 2024-01-23 à 19 24 57" src="https://github.com/batsimadz/Sankofa-Display/assets/32390132/5705f4a7-c526-4f01-89c5-3562c9ea8f94">

- [ ] top hoop and triangle part of Glottalstop is too thick
<img width="347" alt="Capture d’écran 2024-01-23 à 19 25 45" src="https://github.com/batsimadz/Sankofa-Display/assets/32390132/192fb4e9-e94b-4e1e-91f9-6352585adf04">

- [ ] triangle parts of question marks are too thick, and bullet is too thin
<img width="373" alt="Capture d’écran 2024-01-23 à 19 32 29" src="https://github.com/batsimadz/Sankofa-Display/assets/32390132/7d368618-56bc-447f-ae16-b0eb8b495dba">

**Comment by batsimadz** [comment]
Issues fixed thanks!
