### ISSUE TITLE
Glyphs proportions and heights

### ISSUE THREAD

**Issue by LisaHuang2017** [batsimadz/Sankofa-Display#11]
From the file of Sankofa as of Jan 23, 2024, here are my comments on some proportions of glyphs:
- [ ] Chi-latin should be more aligned to the capital height 
<img width="814" alt="Capture d’écran 2024-01-23 à 19 24 01" src="https://github.com/batsimadz/Sankofa-Display/assets/32390132/3ca77c9c-ded3-4cd1-a36f-69c2356cf15b">

- [ ] Strikethrough in Sobliquestroke is too long (it might just fit within the S instead of going beyond its sides, and can be a bit more upright)
<img width="256" alt="Capture d’écran 2024-01-23 à 19 27 09" src="https://github.com/batsimadz/Sankofa-Display/assets/32390132/1483d0d8-f105-4ea3-9ae7-aaee220bf39a">

- [ ] bottom of Thorn doesn't seem to get to the baseline like P
<img width="387" alt="Capture d’écran 2024-01-23 à 19 27 31" src="https://github.com/batsimadz/Sankofa-Display/assets/32390132/86f3f7fa-9f50-4b92-92ba-fa7be1cc4822">

- [ ] descenders are a bit inconsistent on many letters (here are just a few of them)
<img width="660" alt="Capture d’écran 2024-01-23 à 19 28 27" src="https://github.com/batsimadz/Sankofa-Display/assets/32390132/
<img width="277" alt="Capture d’écran 2024-01-23 à 19 31 13" src="https://github.com/batsimadz/Sankofa-Display/assets/32390132/9348ffc5-30a9-43e5-8d6e-1ee5bc0b4103">
75224f8c-bd7b-440d-9722-3543ed8ad5bd">

**Comment by LisaHuang2017** [comment]
Also these: 
- [ ] Omega-latin and Upsilon-latin are too different from each other (one could be the upside down of the other)
<img width="349" alt="Capture d’écran 2024-01-23 à 19 28 51" src="https://github.com/batsimadz/Sankofa-Display/assets/32390132/314dfcf1-7fe7-4bfd-a472-784d66505cb8">

- [ ] chi-latin is too wide compared to the other lowercase letters
<img width="247" alt="Capture d’écran 2024-01-23 à 19 29 41" src="https://github.com/batsimadz/Sankofa-Display/assets/32390132/81ca0f44-52ce-4708-9202-fa2bbea2416f">

**Comment by batsimadz** [comment]
Thanks Lisa, done!
