### ISSUE TITLE
Fontbakery checks needing attention

### ISSUE THREAD

**Issue by n8willis** [batsimadz/Sankofa-Display#14]
Several of the Fontbakery checks ([via recent report](https://github.com/batsimadz/Sankofa-Display/blob/gh-pages/fontbakery/fontbakery-report.md)) will likely need addressing. These are currently at "Warn" level.

- Check the `name` table strings: both the RFN appearance and the missing space in "SankofaDisplay"
- Unreachable glyphs: the `.alt` variants should be handled pretty straightforward in an OpenType feature
- The decomposed "Lcaron" should stay in composed form unless the design precludes it
- soft-dotted characters should lose their dots in the diacritic-carry forms

Slightly less vital, but still a really good idea long-term, is registering yourself (or your chosen foundry name) with a VendorID for the `achVendID` field.

The ScriptLangTags and METADATA subsets are for later, but you can define those, especially if you're interested in ensuring what appears in the `meta` table. (Both `meta` and the VendorID aren't super relevant for live fonts served through Google Fonts, but will be useful for people who download the font files.)

The colinearity, semi-horizontal/vertical, jaggyness, and contour-count checks are not of big concern because of the design, but it is important to scan through them and make sure that no unintended artifacts slip through among all the glyphs that are working-as-intended on those factors.

**Comment by batsimadz** [comment]
- [x] Check the name table strings: both the RFN appearance and the missing space in "SankofaDisplay"

- [x] Unreachable glyphs: the .alt variants should be handled pretty straightforward in an OpenType feature

- [x] The decomposed "Lcaron" should stay in composed form unless the design precludes it

- [x] Soft-dotted characters should lose their dots in the diacritic-carry forms

- [x] Slightly less vital, but still a really good idea long-term, is registering yourself (or your chosen foundry name) with a VendorID for the achVendID field.

- [x]  The ScriptLangTags and METADATA subsets are for later, but you can define those, especially if you're interested in ensuring what appears in the meta table. (Both meta and the VendorID aren't super relevant for live fonts served through Google Fonts, but will be useful for people who download the font files.)
