### ISSUE TITLE
Design goals for .notdef and dotted circle

### ISSUE THREAD

**Issue by n8willis** [batsimadz/Sankofa-Display#16]
The .notdef and dotted-circle glyph have some fairly strict requirements on them.

Mainly, they are both supposed to only be seen by the user when something is broken, so you don't want them to blend in too much with the design of the normal glyphs.

Size-wise, the .notdef looks correct; they are generally cap-height and on the baseline. But the texture and stroke-weight may be misleading for this typeface, considering how many rectangular designs there are for the other glyphs. Better to make it a little bolder and more plain (perhaps even entirely plain); people will want it to jump out at them in their documents if they've tried to type something not supported.

The dotted circle is supposed to be similarly plain-looking, so the glyph in the font works there. But it does need to be scaled up to cap-height. Here again, it's going to stick out because of  that, but that's what it's supposed to do.

**Comment by n8willis** [comment]
Possibly related, I think @tphinney had implied in a conversation earlier that you'd want the dotted circle to have all the anchor points used by different diacritics and marks. But I'm not sure if that's a requirement or just common practice just-in-case.

**Comment by batsimadz** [comment]
Done! I've corrected the glyphs and added anchors on the dottedCircle.
