### ISSUE TITLE
Octopus testing: mising glyphs

### ISSUE THREAD

**Issue by n8willis** [batsimadz/Sankofa-Display#18]
This is a list of glyphs (or base+combining-mark sequences) that show up as missing in Octopus tests with the "African Kern Test Starting with GF African Pri" test file.

The ones where there's a "COMBINING" entry by itself indicate that it's a sequence formed by the                                                         previous letter + the combining mark, so those are separated with an extra line to be clearer. Those cases might just be fixable with a check that there is an anchor on both the base and the mark.

```
glyph   name
ǻ      LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
ƃ      LATIN SMALL LETTER B WITH TOPBAR

d      LATIN SMALL LETTER D
̪      COMBINING BRIDGE BELOW

ƌ      LATIN SMALL LETTER D WITH TOPBAR
ȡ      LATIN SMALL LETTER D WITH CURL
ĕ      LATIN SMALL LETTER E WITH BREVE
ŏ      LATIN SMALL LETTER O WITH BREVE
ǽ      LATIN SMALL LETTER AE WITH ACUTE
ĭ      LATIN SMALL LETTER I WITH BREVE

ĕ      LATIN SMALL LETTER E WITH BREVE
́      COMBINING ACUTE ACCENT

ƕ      LATIN SMALL LETTER HV
ŀ      LATIN SMALL LETTER L WITH MIDDLE DOT
ẛ      LATIN SMALL LETTER LONG S WITH DOT ABOVE
ſ      LATIN SMALL LETTER LONG S
ȿ      LATIN SMALL LETTER S WITH SWASH TAIL
ẙ      LATIN SMALL LETTER Y WITH RING ABOVE
ʀ      LATIN LETTER SMALL CAPITAL R
ẟ      LATIN SMALL LETTER DELTA
ŉ      LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
ȵ      LATIN SMALL LETTER N WITH CURL

ᵻ      LATIN SMALL CAPITAL LETTER I WITH STROKE
'      APOSTROPHE

ẹ      LATIN SMALL LETTER E WITH DOT BELOW
̣      COMBINING DOT BELOW
́      COMBINING ACUTE ACCENT

l      LATIN SMALL LETTER L
̪      COMBINING BRIDGE BELOW

ĭ      LATIN SMALL LETTER I WITH BREVE
ˠ      MODIFIER LETTER SMALL GAMMA
ʽ      MODIFIER LETTER REVERSED COMMA
ẹ      LATIN SMALL LETTER E WITH DOT BELOW
ŉ      LATIN SMALL LETTER N PRECEDED BY APOSTROPHE

```

(edit to add some capitals that got cut off accidentally when pasting:)
```
ʽ      MODIFIER LETTER REVERSED COMMA
Ẹ      LATIN CAPITAL LETTER E WITH DOT BELOW

Ĭ      LATIN CAPITAL LETTER I WITH BREVE
Ĕ      LATIN CAPITAL LETTER E WITH BREVE
Ŏ      LATIN CAPITAL LETTER O WITH BREVE

Ṣ      LATIN CAPITAL LETTER S WITH DOT BELOW
̢      COMBINING RETROFLEX HOOK BELOW

Ȿ      Undefined in range Latin Extended-C <--- CAPITAL S WITH SWASH TAIL, I believe; the lookup utility used may be old

ẟ      LATIN SMALL LETTER DELTA
Ʀ      LATIN LETTER YR
Ŀ      LATIN CAPITAL LETTER L WITH MIDDLE DOT
Ƕ      LATIN CAPITAL LETTER HWAIR

L      LATIN CAPITAL LETTER L
̪      COMBINING BRIDGE BELOW

Ǽ      LATIN CAPITAL LETTER AE WITH ACUTE
```

**Comment by n8willis** [comment]
There is a full list of just the diacritic sequences in this comment from @moyogo : https://github.com/googlefonts/glyphsets/issues/147#issuecomment-1839262941

If I understand the discussion right, this list of sequences is "base+mark pairs that do not have their own Unicode codepoint", so they wouldn't show up in the grid of glyph slots visible in Glyphs filters.

**Comment by batsimadz** [comment]
- [x] ǻ      LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
- [x] ƃ      LATIN SMALL LETTER B WITH TOPBAR

- [x] d      LATIN SMALL LETTER D
̪      COMBINING BRIDGE BELOW

- [x] ƌ      LATIN SMALL LETTER D WITH TOPBAR
- [x] ȡ      LATIN SMALL LETTER D WITH CURL
- [x] ĕ      LATIN SMALL LETTER E WITH BREVE
- [x] ŏ      LATIN SMALL LETTER O WITH BREVE
- [x] ǽ      LATIN SMALL LETTER AE WITH ACUTE
- [x] ĭ      LATIN SMALL LETTER I WITH BREVE

- [x] ĕ      LATIN SMALL LETTER E WITH BREVE
́      COMBINING ACUTE ACCENT

- [x] ƕ      LATIN SMALL LETTER HV
- [x] ŀ      LATIN SMALL LETTER L WITH MIDDLE DOT
- [x] ẛ      LATIN SMALL LETTER LONG S WITH DOT ABOVE
- [x] ſ      LATIN SMALL LETTER LONG S
- [x] ȿ      LATIN SMALL LETTER S WITH SWASH TAIL
- [x] ẙ      LATIN SMALL LETTER Y WITH RING ABOVE
- [x] ʀ      LATIN LETTER SMALL CAPITAL R
- [x] ẟ      LATIN SMALL LETTER DELTA
- [x] ŉ      LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
- [x] ȵ      LATIN SMALL LETTER N WITH CURL

- [x] ᵻ      LATIN SMALL CAPITAL LETTER I WITH STROKE
'      APOSTROPHE

- [x] ẹ      LATIN SMALL LETTER E WITH DOT BELOW
̣      COMBINING DOT BELOW
́      COMBINING ACUTE ACCENT

- [x] l      LATIN SMALL LETTER L
̪      COMBINING BRIDGE BELOW

- [x] ĭ      LATIN SMALL LETTER I WITH BREVE
ˠ      MODIFIER LETTER SMALL GAMMA
ʽ      MODIFIER LETTER REVERSED COMMA
- [x] ẹ      LATIN SMALL LETTER E WITH DOT BELOW
- [x] ŉ      LATIN SMALL LETTER N PRECEDED BY APOSTROPHE

- [x] ʽ      MODIFIER LETTER REVERSED COMMA

- [x] Ẹ      LATIN CAPITAL LETTER E WITH DOT BELOW

- [x] Ĭ      LATIN CAPITAL LETTER I WITH BREVE
- [x] Ĕ      LATIN CAPITAL LETTER E WITH BREVE
- [x] Ŏ      LATIN CAPITAL LETTER O WITH BREVE

- [x] Ṣ      LATIN CAPITAL LETTER S WITH DOT BELOW
̢      COMBINING RETROFLEX HOOK BELOW

- [x] Ȿ      Undefined in range Latin Extended-C <--- CAPITAL S WITH SWASH TAIL, I believe; the lookup utility used may be old

- [x] ẟ      LATIN SMALL LETTER DELTA
- [x] Ʀ      LATIN LETTER YR
- [x] Ŀ      LATIN CAPITAL LETTER L WITH MIDDLE DOT
- [x] Ƕ      LATIN CAPITAL LETTER HWAIR

- [x] L      LATIN CAPITAL LETTER L
̪      COMBINING BRIDGE BELOW

- [x] Ǽ      LATIN CAPITAL LETTER AE WITH ACUTE

**Comment by batsimadz** [comment]
@n8willis Please have a look thanks
