### ISSUE TITLE
Numerals feedback

### ISSUE THREAD

**Issue by n8willis** [batsimadz/Sankofa-Display#2]
Some feedback on the (full-size) numerals!

Shapes:
- Forms that have a diagonal at either the top or bottom should get some overshoot, like the letters do. Definitely needed in zero (both), seven (bottom), and nine (bottom), which have a bit of a "floating" feel to them when used in a string. Possibly the tops of 4 and 6 as well, but that needs judging after adding overshoot to the others.
- The forms that have rectangular counters to them need to balance those counter sizes. Compare the "box" in six and nine to the box in five. (Obviously in this design, the top of five has a triangle in it.)
  - If regularizing that affects the angle of the leg on nine, that leg could descend a bit below the baseline to compensate. Similar option their with the diagonal on six.
- The foot/base of seven is a bit too far to the left. It shouldn't be centered, but in a row of sevens, it's too far visually.
- Overall, one is too light.That might be because the dot is slightly too far away, but the overall tonal value is light enough that it might just need something else added to grab the eye of the reader a little more; it could get lost.

Widths:
- A few of the numerals are noticeably narrower than others; I think the widest is zero at 414 (which is appropriate for this design), but the others need to be closer to each other. That will make spacing them much easier to dial in.

Spacing:
- All the numerals need to have the same (in this case, literally identical) overall width; i.e., tabular spacing. You can do non-tabular spacing as an OpenType feature if you like.
- Zero is the widest, which is appropriate. So set a row of zeros, then below that add a sequence of zeros within a line of text, and adjust the sidebearings of zero from there. But once you have that total glyph+sidebearings width, that has to be the total width for all the other numerals too.
  - Like we had chatted about earlier, the numerals kind of behave according to their own rules, readability-wise, so don't let the 
numbers-in-text proofing overrule what looks right in number-to-number proofs for sure.
- The identical total-widths MAY very well mean that some of the other numerals need to be tweaked so that they don't appear over-crowded or too sparse.
  - Definitely you'll want to test rows of each numeral by itself plus some columns of numerals to assess the visual centering. There's not a lot of shortcuts to take advantage of, beyond the fact that half of the numerals have fairly symmetrical sides..

![numerals-NW-feedback](https://github.com/batsimadz/Sankofa-Display/assets/2192132/e20f5f53-ac67-4ebb-9baa-42db23f63427)

**Comment by LisaHuang2017** [comment]
Looking at the figures only in Sankofa, I agree with @n8willis feedback for the balance between the top and bottom halves of some of them (5, 6 and 9 especially). 
Maybe 4 could be more simplified?
And 7 could have a broken diagonal, like what you did on V or X.

<img width="1018" alt="Capture d’écran 2023-12-07 à 16 22 14" src="https://github.com/batsimadz/Sankofa-Display/assets/32390132/c964edbc-30d8-4978-9c8a-150138529b35">

**Comment by batsimadz** [comment]
@LisaHuang2017 @n8willis 

Hi guys, thanks for the feedback! I have made the tweaks to the numerals. Please have a look thanks.
