### ISSUE TITLE
Confusability with "n"

### ISSUE THREAD

**Issue by n8willis** [batsimadz/Sankofa-Display#4]
There's a potential misread / confusability issue with lowercase 'n' that needs addressing. The construction can read as an "a" — it's quite similar to the way "a" is drawn in "chancery" styles, for example, and the overall look of a straight stem on the right with a loop attaching on the left reads like an "a" construction.

This is a bit like the earlier comments about more clearly distinguishing between S and 5 (for example), where they may work fine in words and sentences, because there is surrounding context to provide visual guidance to a reader, but in a postcode, they would be confusable.

Here, think about text elements that also don't provide the same level of context, like a URL or an email address. Without those cues, the readers can misread something, like here:
<img width="415" alt="Screen Shot 2023-12-14 at 9 17 35 AM" src="https://github.com/batsimadz/Sankofa-Display/assets/2192132/3de11abe-6954-4d3f-961d-ea22b6193895">

If you didn't know the system, you might read that as abc.com (which exists), instead of nbc.com. Artificial example, but URLs and email addresses include a lot of abbreviations & acronyms, so it can happen.

A side-effect of this is that the nleg ends up very close in form to the q:
<img width="384" alt="Screen Shot 2023-12-14 at 9 26 08 AM" src="https://github.com/batsimadz/Sankofa-Display/assets/2192132/16253c3e-5e00-404c-8eed-65d32edb8c91">

As far as how to find a solution goes, the triangle shape is part of the issue, I think.... In other letterforms, the full-width / corner-to-corner triangle is used in letters that have a "full size" closed counter, e.g.:
<img width="365" alt="Screen Shot 2023-12-14 at 9 19 41 AM" src="https://github.com/batsimadz/Sankofa-Display/assets/2192132/b37c0989-5f94-413e-a1fa-807486571e66">

In a and e, where the closed-counter is only "half" the size, the connection point for the diagonal stroke is different. I think that helps, while staying clearly consistent.

So you could move the connection point (upper-right) inward and that might help. Another option would be to incorporate a short in-stroke mark on the upper-left / left stem. I did a SUPER ROUGH paste-up of that (don't be offended...) on both a right-facing and upward-facing stroke, and I think they contribute something, but wouldn't do it entirely on their own.
<img width="406" alt="Screen Shot 2023-12-14 at 9 28 44 AM" src="https://github.com/batsimadz/Sankofa-Display/assets/2192132/31c362b1-77bf-4d23-b6d3-af5bb855e63f">

<img width="537" alt="Screen Shot 2023-12-14 at 9 31 31 AM" src="https://github.com/batsimadz/Sankofa-Display/assets/2192132/5bafe396-b862-455f-ab7e-827e5fd837fe">

So, you might feel like either one of those is worth exploring a little, but I suspect it will take a combination of approaches. You certainly still have other well-defined elements in the visual language of the design that you could drawn on, including the dot and the triangle, as well as trying diagonal orientation on the in-stroke position.

The other big option that you have available to you is to play with the width. Consider how narrow the two internal spaces in the "m" are; the "n" is much wider than those, and that may contribute to it feeling less directly-connected to those shapes. So you could work with (a) narrowing the entire "n" glyph and/or narrowing the triangle of the "n" so that it is visually equal/close-to-equal to the one in "m", with some minor adjustment to the total "n" width so that it matched.

In theory, of course, some people might say that you need to be real precisely similar in "n" to "h" and "u" on width, but I don't think the rest of the design really makes that necessary. If you were to add a vertical in-stroke to the top-left of "n", you'd have to consider raising the ascender height to be sure it reads clearly different. But even without that, I don't think the constructions of "h" and "u" (or "m") need additional adjustment. 

So there are a few avenues to explore; I suspect incorporating more than one technique will be necessary, but only trying it can really show....

**Comment by batsimadz** [comment]
Thanks @n8willis. I have made changes to the n that should address your points above.
