### ISSUE TITLE
H centered anchors need to move right to be centered

### ISSUE THREAD

**Issue by tphinney** [batsimadz/Sankofa-Display#5]
In the cap H, both the "top" and "center" anchors seems to need to go about 17-18 units to the right to be properly centered. The advance width is 511, and those two anchors are both at x=238, should probably be at about x=255 or 256

This impacts a number of precomposed accented characters indirectly, their diacritics are “off”

**Comment by batsimadz** [comment]
Fixed and centered the cap H "top" and "center" anchors.
