### ISSUE TITLE
acutecomb and gravecomb anchors need shifting

### ISSUE THREAD

**Issue by tphinney** [batsimadz/Sankofa-Display#6]
These combining accents, instead of being horizontally aligned so close to their bottom corner, should align noticeably closer (but not at) the middle. So for example the acutecomb has ink from x = 34 to 181, and the anchor at 76 or about 1/4 of the way across the inked part. Try about 20 units further right.

Then do the reverse on the gravecomb.  :)

Note: hungarumlautcomb seems about right in this regard, already.

**Comment by batsimadz** [comment]
Shifted the acutecomb and gravecomb anchors.
