### ISSUE TITLE
Design feedback (JAN 06, 2024)

### ISSUE THREAD

**Issue by LisaHuang2017** [batsimadz/Sankofa-Display#7]
These are new feedback on the Glyphs file of Sankofa as of the end of December 2023.
General comments: there are very few tweaks that need to be done. Mainly issues about alignment of the diacritics (might be some missing work with the components and anchor positions).

[Sankofa_fb_Lisa_060123.pdf](https://github.com/batsimadz/Sankofa-Display/files/13850466/Sankofa_fb_Lisa_060123.pdf)

- [x] diacritics alignment with each other: they need to be all aligned on the same level.
- [x] diacritics alignment with their letter: more centered
- [x] letters with stroke strike through: maybe a more slanted stroke can help by crossing less parts of the letter and bring more legibility?
- [x] narrower AE and OE
- [x] narrower J
- [x] iota: its bottom right serif is too long, it's too assymetrical
- [x] Lcaron: the commaaccent should be closer to the right side (look a words in Czech language containing that letter to have an in use idea)
- [x] hooks and horns: they tend to always clash with the following letter. Maybe they could be shorter but starting higher up above the capital height
- [x] reversed e: they look too similar to the "a". A different structure would help differentiate both.
- [x] ligatures ffi, ffl, fl: make sure to keep the same spacing in between all letters of these ligatures
- [x] theta: it is not a superior glyph, it is to the same level and proportions as pi, delta, etc.
- [x] some strokes are too thin, make sure to have them all consistent by zooming in and out, or using the blur toggle at the bottom of the preview bar
- [x] currency symbols: there should be the same distance between the two bars of all currency symbols (whenever they do have two)
- [x] notequal and approximate: these are part of the mathematical symbols just like equal, multiply, etc. , and should be consistent

**Comment by batsimadz** [comment]
Thanks for the feedback Lisa. All done!
